import type { ActivityLogEntry } from '../../domain/activity-log';

export const testProfileId = 'df6f88b6-10c7-43d7-b516-a063b77db6c6';

/** Privacy-safe fixtures for activity-log presentation tests only. */
export const activityLogTestEntries: readonly ActivityLogEntry[] = [
  {
    action: 'Initialize',
    applicationVersion: '0.0.2',
    browserTarget: 'Edge v.140.0.0',
    category: 'Application',
    dataChanged: false,
    durationMs: 48,
    eventCode: 'APP-PREFLIGHT-COMPLETE',
    id: '11111111-1111-4111-8111-111111111111',
    itemType: 'Application state',
    itemsAffected: 0,
    kind: 'ACTIVITY',
    level: 'INFO',
    message: 'Application preflight completed.',
    operationId: 'op-preview-a14f',
    outcome: 'Succeeded',
    profileId: testProfileId,
    schemaVersion: 2,
    source: 'Application preflight',
    timestamp: Date.now(),
  },
  {
    action: 'Check capability',
    applicationVersion: '0.0.2',
    browserTarget: 'Edge v.140.0.0',
    category: 'Bookmarks',
    dataChanged: false,
    durationMs: 12,
    eventCode: 'BOOKMARK-CAPABILITY-UNAVAILABLE',
    id: '22222222-2222-4222-8222-222222222222',
    itemType: 'Browser bookmarks API',
    itemsAffected: 0,
    kind: 'DIAGNOSTIC',
    level: 'WARN',
    message: 'Browser bookmark capability is unavailable in this preview.',
    operationId: 'op-preview-b27c',
    outcome: 'Skipped',
    profileId: testProfileId,
    schemaVersion: 2,
    source: 'Webpage preview',
    timestamp: Date.now() - 1_000,
  },
  {
    action: 'Update',
    applicationVersion: '0.0.2',
    browserTarget: 'Edge v.140.0.0',
    category: 'Profiles',
    dataChanged: true,
    durationMs: 31,
    eventCode: 'PROFILE-UPDATE-COMPLETE',
    id: '33333333-3333-4333-8333-333333333333',
    itemType: 'Profile settings',
    itemsAffected: 1,
    kind: 'ACTIVITY',
    level: 'INFO',
    message: 'A local profile operation completed.',
    operationId: 'op-local-c93d',
    outcome: 'Succeeded',
    profileId: testProfileId,
    schemaVersion: 2,
    source: 'Profile manager',
    timestamp: Date.now() - 86_400_000,
  },
  {
    action: 'Load',
    applicationVersion: '0.0.2',
    browserTarget: 'Edge v.140.0.0',
    category: 'Application',
    dataChanged: false,
    durationMs: 76,
    eventCode: 'APP-SETTINGS-LOAD-FAILED',
    id: '44444444-4444-4444-8444-444444444444',
    itemType: 'Application settings',
    itemsAffected: 0,
    kind: 'DIAGNOSTIC',
    level: 'ERROR',
    message: 'Application settings could not be loaded.',
    operationId: 'op-preview-d52e',
    outcome: 'Failed',
    profileId: testProfileId,
    schemaVersion: 2,
    source: 'Settings repository',
    timestamp: Date.now() - 4 * 86_400_000,
  },
];
